### ISSUE TITLE
Doesn't start. MacOS BigSur, bash, 3.8.2, pyenv, x64-i9

### ISSUE THREAD

**Issue by icec102** [dermasmid/py-jsoneditor#1]
python -m jsoneditor '{"Hey": "Hi"}'

Traceback (most recent call last):
  File ".pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ".pyenv/versions/3.8.2/lib/python3.8/site-packages/jsoneditor/__main__.py", line 4, in <module>
    main()
  File ".pyenv/versions/3.8.2/lib/python3.8/site-packages/jsoneditor/jsoneditor.py", line 53, in main
    editjson(data)
  File ".pyenv/versions/3.8.2/lib/python3.8/site-packages/jsoneditor/jsoneditor.py", line 41, in editjson
    server.start()
  File ".pyenv/versions/3.8.2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File ".pyenv/versions/3.8.2/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File ".pyenv/versions/3.8.2/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File ".pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File ".pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File ".pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File ".pyenv/versions/3.8.2/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'editjson.<locals>.jsoneditor_route'
$

**Comment by dermasmid** [comment]
this looks to be a macos specific issue so i can"t test my fix, can you please download [this](https://github.com/dermasmid/py-jsoneditor/tree/issue-1) branch and run `python tests/test.py` and report back if it works

**Comment by dermasmid** [comment]
fixed in new release
